nodeLinker: pnp

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
