nodeLinker: pnp

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  "@next/font@*":
    dependencies:
      next: "*"
  next@*:
    dependencies:
      "@next/font": "*"
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
